#VYOS Configuration Playbook
- name: vyos network config
  host: vyos
  tasks:
    - name: load vyos config from template
    become: yes
    template: 
      src: files/vyos/config.boot.j2
      dest: /config/config.boot
      mode: "0775"
      owner: root
      group: vyattacfg
    - name: bounce and end
      become: yes
      shell: nohup bash -c "usr/bin/sleep 5 && /usr/sbin/shutdown -r now" &
